### ISSUE TITLE
Add line numbering on paragraph hover

### ISSUE THREAD

**Issue by tomzx** [tomzx/blog.tomrochette.com#77]
On `p`/`li`/`h*` in the `.articleBody`.

```CSS
p:before {
	content: "1234";
	float: left;
	text-align: right;
	margin-left: -65px;
}
```
